### ISSUE TITLE
rpmdev-extract broken, fails to extract rpm files

### ISSUE THREAD

**Issue by d-musique** [OpenMandrivaAssociation/distribution#3280]
**OpenMandriva version**:
OpenMandriva Lx release 25.06 (ROME) Rolling for x86_64

**Describe the bug**:
Trying to extract a SRPM using `rpmdev-extract` invokes `cpio` with option `--no-absolute-filenames`.
The `cpio` command does not recognize the flag, prints usage, and quits.
Despite failure, rpmdev-extract exits with 0, and no file is extracted.

**Steps to reproduce**:
Get SRPM (ie. `ninja-1.12.1-1.src.rpm`)
Run `rpmdev-extract ninja-1.12.1-1.src.rpm`

**Observed behavior**:
This console output:
```
ninja-1.12.1-1.src/cpio: Option --no-absolute-filenames is not supported
ninja-1.12.1-1.src/Brief Usage:
ninja-1.12.1-1.src/  List:    cpio -it < archive
ninja-1.12.1-1.src/  Extract: cpio -i < archive
ninja-1.12.1-1.src/  Create:  cpio -o < filenames > archive
ninja-1.12.1-1.src/  Help:    cpio --help
```

**Expected behavior**:
Files are extracted.

**Additional comment**:
```
cpio.x86_64                                             3.7.9-1                   rolling-x86_64
rpmdevtools.noarch                                      9.6-2                     rolling-x86_64
```

**Comment by d-musique** [comment]
I also have discovered another relevant fact: /usr/bin/cpio links to the BSD version of cpio instead rather than the GNU one
`lrwxrwxrwx 1 root root 7 avril 18 22:25 /usr/bin/cpio -> bsdcpio*`

**Comment by d-musique** [comment]
> This seems more like a workflow problem, and it might make more sense to discuss what the goal is and the source of the information you are using.

Well the tool `rpmdev-extract` is a shell script which invokes BSD cpio, and the flag in question appears to be GNU-only.
By editing that script to replace the 2 `cpio` occurrences with `gcpio` from package `gnucpio`, this problem is fixed.

The most obvious way to fix the problem seems to add the `gnucpio` dependency and to patch.

**Note**

Based on a quick local grep search, there may be other programs affected similarly, that also would need patching.
`sudo grep -r -F -s no-absolute-filenames /usr/`

---

`rpmpeek`, also from `rpmdevtools`

```
/usr/bin/rpmpeek:        $fakeroot_save cpio -idmu --quiet --no-absolute-filenames;
```
---

`engrampa`
see: https://github.com/mate-desktop/engrampa/blob/ab1324372b8d9ba7f11a7b5f5d35da7e3f4c3924/src/fr-command-cpio.c#L200

---

`dracut`

```
/usr/lib/dracut/dracut-initramfs-restore:if (command -v zcat > /dev/null && $SKIP "$IMG" 2> /dev/null | zcat 2> /dev/null | cpio -id --no-absolute-filenames --quiet > /dev/null 2>&1) \
```

**Comment by ZeroAbility** [comment]
Here is the package spec for `rpmdevtools`:
https://github.com/OpenMandrivaAssociation/rpmdevtools

The last release was 3 years ago, and the last commit before the one 6 months ago was 2 years ago. Hopefully, they will continue the project or we may have to discuss alternatives. In the meantime, feel free to submit a PR with the fix for the option flag so it can be used with `bsdcpio`. Similar with the other software you mentioned:

https://github.com/OpenMandrivaAssociation/engrampa
https://github.com/OpenMandrivaAssociation/dracut

Some of the devs might want to weigh in on the issues and it would help to tell us what your goal is, what documentation you are referring to, and any other specific cases where you are getting errors like this.

**Comment by d-musique** [comment]
> In the meantime, feel free to submit a PR with the fix for the option flag so it can be used with bsdcpio

If the manual page `bsdcpio(1)` is correct, the flag can be removed, because bsdcpio has security measures enabled by default.

>        --insecure
>                (i  and  p mode only) Disable security checks during extraction or copying.
>                This allows extraction via symbolic links, absolute paths, and path names containing ‘..’ in the name.

**Comment by ZeroAbility** [comment]
We can see about patching that out. I'd like to wait and see if they continue committing to the project, first.

**Comment by ZeroAbility** [comment]
It still doesn't look like they will be releasing another version. We have since moved on to using `packaging-tools`. There are many other ways to extract a rpm.
